# database.yml
development:

  encoding: utf8
  adapter: postgresql
  database: db/splitwise
  pool: 5
  timeout: 5000
production:

  encoding: utf8
  adapter: postgresql
  database: db/splitwise
  pool: 5
  timeout: 5000
